### ISSUE TITLE
[Panic] github.com/cosmtrek/air/runner.(*Engine).cacheFileChecksums

### ISSUE THREAD

**Issue by Akkadius** [cosmtrek/air#189]
When a go file changes under Windows; we get a panic

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x12d999]

goroutine 181 [running]:
github.com/cosmtrek/air/runner.(*Engine).cacheFileChecksums.func1({0xc000672080, 0x33}, {0x0, 0x0}, {0x197020, 0xc000022090})
        C:/Users/cmiles/go/pkg/mod/github.com/cosmtrek/air@v1.27.3/runner/engine.go:140 +0x59
path/filepath.walk({0xc00049fe00, 0x29}, {0x199e18, 0xc0002833b0}, 0xc000579e68)
        C:/Program Files/Go/src/path/filepath/path.go:438 +0x20d
path/filepath.Walk({0xc00049fe00, 0x29}, 0xc000579e68)
        C:/Program Files/Go/src/path/filepath/path.go:505 +0x6c
github.com/cosmtrek/air/runner.(*Engine).cacheFileChecksums(0x0, {0xc00049fe00, 0x0})
        C:/Users/cmiles/go/pkg/mod/github.com/cosmtrek/air@v1.27.3/runner/engine.go:138 +0x45
github.com/cosmtrek/air/runner.(*Engine).watchDir.func1()
        C:/Users/cmiles/go/pkg/mod/github.com/cosmtrek/air@v1.27.3/runner/engine.go:211 +0xde
created by github.com/cosmtrek/air/runner.(*Engine).watchDir
        C:/Users/cmiles/go/pkg/mod/github.com/cosmtrek/air@v1.27.3/runner/engine.go:200 +0x252
```

**Comment by xiantang** [comment]
fixed in  https://github.com/cosmtrek/air/pull/209
