### ISSUE TITLE
panic (close of closed channel) after Ctrl + C 

### ISSUE THREAD

**Issue by mateusz834** [cosmtrek/air#294]
```
[mateusz@arch t2 ]$ air -d

  __    _   ___  
 / /\  | | | |_) 
/_/--\ |_| |_| \_ , built with Go 

[debug] mode
CWD: /home/mateusz/Desktop/test/t2
watching .
watching dist
!exclude node_modules
!exclude tmp
building...
running...
running process pid 50114
hello
event: "/home/mateusz/Desktop/test/t2/main.go": WRITE
main.go has changed
event: "/home/mateusz/Desktop/test/t2/main.go": WRITE
main.go has changed
flushing events
main.go has changed
building...
trying to kill pid 50114, cmd [/bin/sh -c /home/mateusz/Desktop/test/t2/tmp/main]
cmd killed, pid: 50114
# tets
./main.go:8:1: syntax error: unexpected }, expecting name or (
failed to build, error: exit status 2
event: "/home/mateusz/Desktop/test/t2/main.go": WRITE
main.go has changed
event: "/home/mateusz/Desktop/test/t2/main.go": WRITE
main.go has changed
flushing events
main.go has changed
building...
running...
running process pid 50364
hello
^Cexit in start
cleaning...
wating for      close watchers..
trying to kill pid 50364, cmd [/bin/sh -c /home/mateusz/Desktop/test/t2/tmp/main]
cmd killed, pid: 50364
waiting for buildRun...
exit in killFunc
waiting for clean ...
panic: close of closed channel

goroutine 13 [running]:
github.com/cosmtrek/air/runner.(*Engine).runBin.func2.1()
        /home/mateusz/go/pkg/mod/github.com/cosmtrek/air@v1.40.1/runner/engine.go:444 +0x5e
github.com/cosmtrek/air/runner.(*Engine).runBin.func2(0xc000174160, {0x570ae8, 0xc00000e088}, {0x570ae8, 0xc00000e088})
        /home/mateusz/go/pkg/mod/github.com/cosmtrek/air@v1.40.1/runner/engine.go:466 +0x662
created by github.com/cosmtrek/air/runner.(*Engine).runBin.func3
        /home/mateusz/go/pkg/mod/github.com/cosmtrek/air@v1.40.1/runner/engine.go:475 +0x145
```
How to reproduce: 
1) run air normally
2) edit *.go file to create build error
3) wait for error
4) fix build error (revert changes)
5) Ctrl + C

**Comment by xiantang** [comment]
let me take a look thx

**Comment by mateusz834** [comment]
Channel is closed after build error here: https://github.com/cosmtrek/air/blob/4612c12f1ed7c899314b8430bc1d841ca2cb061a/runner/engine.go#L371
and after ctrl+c here: https://github.com/cosmtrek/air/blob/4612c12f1ed7c899314b8430bc1d841ca2cb061a/runner/engine.go#L445

**Comment by mateusz834** [comment]
It also happens after two failed builds
