### ISSUE TITLE
sigsegv when using conf

### ISSUE THREAD

**Issue by nihiluis** [cosmtrek/air#5]
starting with `~/.air` on arch linux. go 1.9.2

```
Live reload for Go apps :)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4fc7a2]

goroutine 1 [running]:
github.com/cosmtrek/air/runner.(*Engine).watching.func1(0xc420018180, 0x32, 0x0, 0x0, 0x5e44c0, 0xc42005c5d0, 0x10, 0x5248e0)
	/Users/cosmtrek/Code/go/src/github.com/cosmtrek/air/runner/engine.go:100 +0x32
path/filepath.Walk(0xc420018180, 0x32, 0xc42000f650, 0x6, 0xc420018180)
	/usr/local/opt/go/libexec/src/path/filepath/path.go:401 +0x76
github.com/cosmtrek/air/runner.(*Engine).watching(0xc420072180, 0xc420018180, 0x32, 0xc42000f630, 0x1)
	/Users/cosmtrek/Code/go/src/github.com/cosmtrek/air/runner/engine.go:98 +0x76
github.com/cosmtrek/air/runner.(*Engine).Run(0xc420072180)
	/Users/cosmtrek/Code/go/src/github.com/cosmtrek/air/runner/engine.go:77 +0xf3
main.main()
	/Users/cosmtrek/Code/go/src/github.com/cosmtrek/air/main.go:52 +0x1ea
```

using this .air.conf

```
# working directory
root = "." # . or absolute path, please note that the directories following must be under root
watch_dir = "runner" # optional, if no watch_dir, use root
tmp_dir = "tmp"

[build]
exclude_dir = ["node_modules"]
delay = 800 # ms

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
app = "white"
```

or this
```
# conf for Air in toml format

# working directory
root = "." # . or absolute path, please note that the directories following must be under root
watch_dir = "runner" # optional, if no watch_dir, use root
tmp_dir = "tmp"

[build]
bin = "tmp/server"
cmd = "go build -o ./tmp/server ./cmd/server"
log = "server-errors.log" # this log file places in your tmp_dir
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
delay = 800 # ms

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
app = "white"
```

**Comment by leeyongda** [comment]
@nihiluis 
## .ari.conf (custome conf)

> ## watch_dir = ""   # set empty directory is ok;

## .air.conf (Example):
![qq20180226-213548](https://user-images.githubusercontent.com/11832476/36673241-1a1fa480-1b3d-11e8-808c-46afab52a0ef.png)
## air in your project root directory:
![qq20180226-214340](https://user-images.githubusercontent.com/11832476/36673585-2d3186dc-1b3e-11e8-9b5c-7c40c794c3a7.png)

## Then Run is Ok:
![qq20180226-214233](https://user-images.githubusercontent.com/11832476/36673533-03df6646-1b3e-11e8-9db2-9b0207221ba8.png)

**Comment by cosmtrek** [comment]
@leeyongda Big thanks!

**Comment by nihiluis** [comment]
app should not sigsegv but display an error.

**Comment by cosmtrek** [comment]
@nihiluis  I'll fix this, thanks~
