### ISSUE TITLE
Runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lokhman** [cosmtrek/air#7]
Constantly getting the following error after any file amend:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4f1aa2]

goroutine 23 [running]:
github.com/cosmtrek/air/runner.(*Engine).watching.func1(0xc4200d8780, 0x4b, 0x0, 0x0, 0x553860, 0xc4200d0360, 0x0, 0x0)
        /Users/cosmtrek/Code/go/src/github.com/cosmtrek/air/runner/engine.go:100 +0x32
path/filepath.walk(0xc420018004, 0x37, 0x5542e0, 0xc4200d3040, 0xc4200de2e0, 0x0, 0x10)
        /usr/local/opt/go/libexec/src/path/filepath/path.go:377 +0x20d
path/filepath.Walk(0xc420018004, 0x37, 0xc4200de2e0, 0x0, 0xc42003cfc8)
        /usr/local/opt/go/libexec/src/path/filepath/path.go:403 +0x106
github.com/cosmtrek/air/runner.(*Engine).watching(0xc4200f0000, 0xc420018004, 0x37, 0x0, 0x0)
        /Users/cosmtrek/Code/go/src/github.com/cosmtrek/air/runner/engine.go:98 +0x74
github.com/cosmtrek/air/runner.(*Engine).watchNewDir.func1(0xc4200f0000, 0xc420018004, 0x37)
        /Users/cosmtrek/Code/go/src/github.com/cosmtrek/air/runner/engine.go:179 +0x43
created by github.com/cosmtrek/air/runner.(*Engine).watchNewDir
        /Users/cosmtrek/Code/go/src/github.com/cosmtrek/air/runner/engine.go:178 +0x36a
```
**OS:** Windows x64 and Ubuntu 16.04 LTS (Windows subsystem)

**Comment by cosmtrek** [comment]
Could you provide me more info to reproduce it?

**Comment by vferdiansyah** [comment]
I have similar issue here. Happens after a fresh install by following the installation guide on MacOS.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10f16c2]

goroutine 1 [running]:
github.com/cosmtrek/air/runner.(*Engine).watching.func1(0xc42010c0f0, 0x4d, 0x0, 0x0, 0x1152820, 0xc4200c6270, 0x10, 0x1118760)
	/Users/cosmtrek/Code/go/src/github.com/cosmtrek/air/runner/engine.go:100 +0x32
path/filepath.Walk(0xc42010c0f0, 0x4d, 0xc4200e71d0, 0xc42010c0f0, 0x4d)
	/usr/local/opt/go/libexec/src/path/filepath/path.go:401 +0x6c
github.com/cosmtrek/air/runner.(*Engine).watching(0xc420116000, 0xc42010c0f0, 0x4d, 0xc4200e71b0, 0x1)
	/Users/cosmtrek/Code/go/src/github.com/cosmtrek/air/runner/engine.go:98 +0x74
github.com/cosmtrek/air/runner.(*Engine).Run(0xc420116000)
	/Users/cosmtrek/Code/go/src/github.com/cosmtrek/air/runner/engine.go:77 +0xf3
main.main()
	/Users/cosmtrek/Code/go/src/github.com/cosmtrek/air/main.go:53 +0x1d8
```

**Comment by cosmtrek** [comment]
@vferdiansyah What's your `air.conf`?

**Comment by vferdiansyah** [comment]
@cosmtrek exactly the same as the sample that you provided on readme.

**Comment by cosmtrek** [comment]
@vferdiansyah  Oops, you need to comment out the `watch_dir` option.

```
# conf for [Air](https://github.com/cosmtrek/air) in TOML format

# working directory
root = "." # . or absolute path, please note that the directories following must be under root
# watch_dir = "" # optional, if no watch_dir, use root
tmp_dir = "tmp"

[build]
bin = "tmp/server"
cmd = "go build -o ./tmp/server ./cmd/server"
log = "server-errors.log" # this log file places in your tmp_dir
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
delay = 800 # ms

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
app = "white"
```

**Comment by lokhman** [comment]
Oh, sorry for late reply. I don’t have any special configuration here: error both in your build and in own build of last version, simple folder with `main` and **no** `app.conf`.

**Comment by vferdiansyah** [comment]
@cosmtrek thanks it works now!

**Comment by cosmtrek** [comment]
@lokhman It needs `air.conf` to works...

**Comment by zekker6** [comment]
Using Windows 10 with WSL and ubuntu 16.04 in it also causes same error
.air.conf

```
# conf for [Air](https://github.com/cosmtrek/air) in TOML format

# working directory
root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/server"
cmd = "go build -o ./tmp/server ./main.go"
log = "server-errors.log"
include_ext = ["go"]
exclude_dir = ["docker", "tmp", "vendor"]
delay = 800

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
app = "white"
```
Current dir: `$ ls -la`
```
  418 Nov  6 19:33 .air.conf   
 4.0K Nov  6 17:09 app         
 4.0K Nov  6 18:18 config      
 4.0K Nov  6 18:18 docker      
 4.0K Nov  6 19:34 .git        
   18 Nov  6 19:24 .gitignore  
 4.6K Nov  6 18:56 Gopkg.lock  
  868 Nov  6 18:56 Gopkg.toml  
 4.0K Nov  6 19:34 .idea       
  482 Nov  6 18:56 main.go     
    0 Sep 27 12:33 README.md   
 4.0K Nov  6 19:33 routes      
 4.0K Nov  6 19:34 tmp         
 4.0K Nov  6 18:56 vendor      
```

Any ideas?
